.github/ISSUE_TEMPLATE/1_feature_request.md
.github/ISSUE_TEMPLATE/2_bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md

Added the PR/Issue templates to enforce a consistent schema
Closes #1

[ResOps] Create PR & Issue Templates

---

.github/CODEOWNERS

Create a basic `CODEOWNERS` files to enforce PR reviews from the correct teams
Closes #6

[DX] Create CODEOWNERS file

---

apps/backend/user/.gitignore
apps/backend/user/Dockerfile
apps/backend/user/package.json
apps/backend/user/src/index.ts
apps/backend/user/tsconfig.json
docker-compose.yml

Created the template for the `user` service built with NodeJS (Typescript), Express.js, and Docker.
Closes #15
```bash
docker-compose up --build
curl localhost:8211/api/user
```

[User] Template User service with Docker config

---

.github/workflows/frontend.yml

Create the base CI jobs for the Frontend service: linting, formatting, testing, building, and security
This PR is stacked on top of #87, so first review that PR (as this diff contains that PR diff also).
Closes #26

 [Frontend] Set up CI: lint, format, test, build, security

---

apps/backend/listing/.gitignore
apps/backend/listing/Dockerfile
apps/backend/listing/package.json
apps/backend/listing/src/index.ts
apps/backend/listing/tsconfig.json
docker-compose.yml

This is a retry of #14 
Closes #14

 [Listing] Set up base project for listing service

---

apps/backend/review/.gitignore
apps/backend/review/Dockerfile
apps/backend/review/package.json
apps/backend/review/src/index.ts
apps/backend/review/tsconfig.json
docker-compose.yml

Created the template for the `review` service built with NodeJS (Typescript), Express.js, and Docker.
Closes #16 
```bash
docker-compose up --build
curl localhost:8211/api/review
```

[Review] RESOPS16 Set up base project for review service

---

apps/backend/message/.gitignore
apps/backend/message/Dockerfile
apps/backend/message/package.json
apps/backend/message/src/index.ts
apps/backend/message/tsconfig.json
docker-compose.yml

This is the base of the backend Message service
Closes #18 
```bash
docker-compose up --build
curl localhost:8211/api/message
```

[Message] RESOPS18 set up base project for messages service

---

.github/workflows/recommend.yml

Adds a workflow for the recommender service.
This is a stacked PR on #98, please review that first.
Closes #24 

[Recommend] RESOPS24 - Create Recommender CI workflow

---

.github/workflows/review.yml
apps/backend/review/eslint.config.mjs
apps/backend/review/jest.config.ts
apps/backend/review/package-lock.json
apps/backend/review/package.json
apps/backend/review/src/index.test.ts
apps/backend/review/src/index.ts

Create the base CI jobs for the Review service: linting, formatting, testing, and security
This PR is stacked on top of #103 , so first review that PR (as this diff contains that PR diff also).
Closes #28  

[Review] RESOPS28 Set up CI for the review service

---

.github/workflows/listing.yml
apps/backend/listing/eslint.config.mjs
apps/backend/listing/jest.config.ts
apps/backend/listing/package-lock.json
apps/backend/listing/package.json
apps/backend/listing/src/index.test.ts
apps/backend/listing/src/index.ts

Create the base CI jobs for the Listing service: linting, formatting, testing, and security
This PR is stacked on top of #101, so first review that PR (as this diff contains that PR diff also).
Closes #27 

[Listing] RESOPS27 - Set up ci for the listings service

---

.github/workflows/message.yml
apps/backend/message/eslint.config.mjs
apps/backend/message/jest.config.ts
apps/backend/message/package-lock.json
apps/backend/message/package.json
apps/backend/message/src/index.test.ts
apps/backend/message/src/index.ts

Create the base CI jobs for the Message service: linting, formatting, testing, and security
This PR is stacked on top of #18 , so first review that PR (as this diff contains that PR diff also).
Closes #30 

[Message] RESOPS30 Set up ci for the message service

---

.github/workflows/user.yml
docker-compose.yml

Docker-compose had an indentation error, now it is resolved

[Fix] Docker Compose indentation error

---

.github/workflows/linked_issues.yml
.github/workflows/pr.yml

Ensures any pull request has an associated issue
Closes #2
Try to merge a PR with an issue, should pass
Try to merge a PR without an issue, should fail
-  [x] I have *actually* self-reviewed my changes and done QA

Create linked issues action

---

apps/data/datalayer/Cargo.lock
apps/data/datalayer/Cargo.toml
apps/data/datalayer/Dockerfile
apps/data/datalayer/src/main.rs
apps/data/datalayer/supervisord.conf
docker-compose.yml

*This PR is built on top of #109, make sure to merge that first*
Adds the rust project to the datalayer and modifies the docker container to run both pgbouncer and rust.
Closes #41
```bash
docker compose up --build
curl localhost:8301
```

[Datalayer] Set up rust project

---

apps/data/elasticsearch/Dockerfile
apps/data/elasticsearch/elasticsearch.yml
docker-compose.yml

Created the docker container for the elasticsearch database
Closes #17 
```bash
docker compose up --build
curl -k https://elastic:serxdfcghjfc@localhost:8311
```

[Elasticsearch] Create the elasticsearch docker

---

apps/backend/lib/.gitignore
apps/backend/lib/eslint.config.mjs
apps/backend/lib/example.ts
apps/backend/lib/jest.config.ts
apps/backend/lib/package-lock.json
apps/backend/lib/package.json
apps/backend/lib/src/example.test.ts
apps/backend/lib/src/example.ts
apps/backend/lib/tsconfig.json
apps/backend/listing/Dockerfile
apps/backend/listing/src/index.ts
apps/backend/review/Dockerfile
apps/backend/review/src/index.ts
apps/backend/user/Dockerfile
apps/backend/user/src/index.ts
docker-compose.yml

Adds a backend/lib folder with a js package and associated docker config
Closes #149 
```bash
docker compose up --build
curl localhost:8213/api/review
```
Should print `Hello World!` to the server console.

[Backend] Create a shared library for the backend services

---

.github/workflows/backend-lib.yml

Adds the github CI for the backend's shared libraries.
Closes #151 

[Backend] Add CI workflow for backend lib

---

.github/workflows/listing.yml
.github/workflows/message.yml
.github/workflows/review.yml

Sets the correct directories for the security scan
Closes #154 

[Backend] Fix security CI

---

apps/backend/lib/package.json
apps/backend/listing/package.json
apps/backend/message/package.json
apps/backend/review/package.json
apps/backend/user/package.json

CI was failing because the `test` command was not picking up any tests to run
Closes #165
Take a look and see CI pass

[CI] Fix Backend CI test jobs failing

---

apps/backend/message/src/index.ts
apps/proxy/Dockerfile
apps/proxy/dynamic_config.yml
apps/proxy/traefik.yml
docker-compose.yml

Created the template for the `proxy` service built with Traefik
Closes #12
```bash
docker-compose up --build
curl localhost
```

[Proxy] Add base service

---

.github/workflows/e2e.yml

Created an `E2E` workflow that runs `docker compose build` & `docker compose up` to make sure that nothing docker related is broken
Closes #132
Observe the passing CI job `E2E/Smoke Test`

[CI] Add docker compose smoketest

---

.github/workflows/security.yml

This adds a workflow using trufflehog to scan for secrets that have been accidentally pushed in a commit.
Closes #134 
Push code to a branch, workflow will run

[SECURITY] RESOPS134 - Secret Scanning workflow

---

.github/workflows/backend-lib.yml
.github/workflows/datalayer.yml
.github/workflows/frontend.yml
.github/workflows/listing.yml
.github/workflows/message.yml
.github/workflows/recommend.yml
.github/workflows/review.yml
.github/workflows/search.yml
.github/workflows/security.yml
.github/workflows/user.yml

Upgrade all instances of `actions/checkout` & `actions/setup-node` to `v4`
Closes #171
Notice no CI warnings now in the `checks` panel

[CI] Upgrade deprecated `Node v16` GH Actions

---

README.md

Added the architecture mermaid diagram & local development instructions to the README
Closes #173

[Docs] Add README architecture & local development

---

.github/workflows/listing.yml
.github/workflows/message.yml
.github/workflows/recommend.yml
.github/workflows/review.yml
.github/workflows/search.yml
.github/workflows/user.yml

Run each `test` CI job within the `docker compose` stack to enable integration tests to pass.
Closes #167
Observe the green checkmarks for CI jobs

[CI] Run integration tests within docker stack

---

docker-compose.yml

Only allows services to communicate with the other services that they are permitted to.
Closes #131
Try to curl a service from within another service

[Security] Restrict network access between services

---

apps/data/elasticsearch/Dockerfile
docker-compose.yml

Makes the search container depend on the elasticsearch container and adds a healthcheck to elasticsearch.
Closes #184 
Run `docker compose up --build`

Make search depend on elasticsearch

---

apps/data/datalayer/Cargo.lock
apps/data/datalayer/Cargo.toml
apps/data/datalayer/src/email.rs
apps/data/datalayer/src/example.rs
apps/data/datalayer/src/main.rs
docker-compose.yml

Creates the send email api
Closes #130
Run `cargo test` or send a post request to the data layer on port 8302 with the json body containing to, subject, and body.

[datalayer] Create email endpoint

---

.github/workflows/algorithm.yml
.github/workflows/backend.yml
.github/workflows/datalayer.yml
.github/workflows/frontend.yml

Added the GuardDog CI job to each service
Closes #136
Observe the green checkmarks for each `Supply Chain Security` CI job

[CI] Add supply chain security job for each service

---

apps/algorithm/recommend/src/training/run.py
apps/algorithm/recommend/src/training/train.py

Recommend based on search terms

---

apps/algorithm/recommend/src/training/run.py
apps/data/database/initdb.sql

Recommend on listing clicked

---

apps/frontend/src/components/Reviews.tsx
apps/frontend/src/pages/ViewListing.tsx
apps/frontend/src/styles/colors.tsx
apps/frontend/tests/component_tests/ViewListing.cy.tsx

Implemented creating and viewing reviews.
Closes #53 
Closes #52

Create and view reviews

---

apps/data/datalayer/Dockerfile
apps/data/elasticsearch/elasticsearch.yml

Reduce logging for elasticsearch and pgbouncer

---

apps/backend/user/Dockerfile
apps/backend/user/cypress.config.ts
apps/backend/user/cypress/e2e/createUserTest.cy.ts
apps/backend/user/cypress/e2e/deleteUserTest.cy.ts
apps/backend/user/cypress/e2e/getUserTest.cy.ts
apps/backend/user/cypress/e2e/loginTest.cy.ts
apps/backend/user/cypress/e2e/logoutTest.cy.ts
apps/backend/user/cypress/e2e/patchUserTest.cy.ts
apps/backend/user/cypress/fixtures/example.json
apps/backend/user/cypress/tsconfig.json
apps/backend/user/package-lock.json
apps/backend/user/package.json
apps/backend/user/src/createUser.ts
apps/backend/user/src/deleteUser.ts
apps/backend/user/src/getUser.ts
apps/backend/user/src/index.ts
apps/backend/user/src/login.ts
apps/backend/user/src/logout.ts
apps/backend/user/src/models/user.ts
apps/backend/user/src/patchUser.ts
apps/backend/user/tsconfig.json
apps/data/database/initdb.sql
apps/data/database/populatedb.sql

All the backend user routes, including login/logout
Closes #90 #91
Run it

Backend user routes

---

apps/data/cache/Dockerfile
docker-compose.yml

Adds the dragonfly container.
Closes #9 

[resops] Add dragonfly cache

---

docker-compose.yml

Remove the commented ports
Closes #218

[FIX] Remove Docker Compose ports being exposed

---

apps/frontend/src/pages/Homepage.tsx

Fixes the url that is being sent for when making searches and fixes the .map() is not a function error on the homepage
Closes #71

Fix API search url and .map error on homepage

---

README.md
test.sh

Adds a bash script that runs all tests in the project.
Closes #210 
run test.sh

[TESTING] RESOPS 210 add test workflow

---

apps/backend/user/src/login.ts

comment out verification check until it is implemented

---

apps/backend/user/cypress/e2e/getUserTest.cy.ts
apps/backend/user/cypress/e2e/patchUserTest.cy.ts
apps/data/database/populatedb.sql

Make the database seed data to be valid email/passwords
Closes #228

[FIX] Database population needs hashed passwords

---

apps/frontend/src/pages/Profile.tsx

set profile picture properly

---

apps/frontend/src/pages/MyListings.tsx
apps/frontend/tests/component_tests/MyListings.cy.tsx

fix listing object format

---

apps/frontend/src/pages/ViewListing.tsx
apps/frontend/tests/component_tests/ViewListing.cy.tsx

Added some features to the view listing page that depended on the user context
- Edit listing instead of message if it's your own listing
- Added SOLD status
- Removed link to user profile
Closes #72 
Run cypress for testing
`npx cypress open`

Added final features for the view listings with user context

---

apps/frontend/src/pages/EditListing.tsx
apps/frontend/tests/component_tests/EditListing.cy.tsx

Fixes the flaky test for editing a listing
Closes #59 
Run cypress
`npx cypress open`

Fixed the flaky test with edit listing

---

apps/frontend/.gitignore
apps/frontend/src/pages/CreateListing.tsx
apps/frontend/src/pages/EditListing.tsx
apps/frontend/src/pages/ViewListing.tsx

Fixed features:
- Added redirect to user's listing on successful creation
- Added update location button to fix issues with synchronous
Closes #73 
Cypress testings

Fixed create listings redirect and location getting

---

apps/frontend/src/components/AccountSidebar.tsx
apps/frontend/src/components/listingCard.tsx
apps/frontend/src/components/searchBar.tsx
apps/frontend/src/pages/Homepage.tsx
apps/frontend/src/pages/MyListings.tsx
apps/frontend/src/pages/MyReviews.tsx
apps/frontend/src/pages/Profile.tsx
apps/frontend/src/styles/colors.tsx
apps/frontend/src/styles/pageStyles.tsx

Fixed stylings/UI

---

apps/frontend/src/components/listingCard.tsx
apps/frontend/src/pages/Homepage.tsx

Fixed spacing btw listings

---

apps/frontend/src/_axios_instance.tsx
apps/frontend/src/components/filters.tsx
apps/frontend/src/pages/Homepage.tsx
apps/frontend/tests/component_tests/Homepage.cy.tsx

Fix search API call

---

apps/algorithm/search/README.md

Added readme for search.
Closes #253

Readme for search

---

apps/frontend/src/App.tsx
apps/frontend/src/components/listingCard.tsx
apps/frontend/src/pages/ViewProfile.tsx
apps/frontend/tests/component_tests/ViewProfile.cy.tsx

Viewing profiles of other users

---

apps/frontend/src/components/Spinner.tsx
apps/frontend/src/pages/EditListing.tsx
apps/frontend/src/pages/ViewListing.tsx
apps/frontend/tests/component_tests/Spinner.cy.tsx
apps/frontend/tests/component_tests/ViewListing.cy.tsx

Adds a component for displaying loading and errors to users.
Closes #272 
Run cypress test

Adds a loading spinner to slow pages

---

apps/frontend/src/components/Spinner.tsx
apps/frontend/src/components/filters.tsx
apps/frontend/src/components/listingCard.tsx
apps/frontend/src/components/searchBar.tsx
apps/frontend/src/pages/Homepage.tsx
apps/frontend/tests/component_tests/Filters.cy.tsx
apps/frontend/tests/component_tests/Homepage.cy.tsx
apps/frontend/tests/component_tests/SearchBar.cy.tsx

Fix search bar bugs

---

apps/frontend/src/components/searchBar.tsx
apps/frontend/src/styles/pageStyles.tsx
apps/frontend/tests/component_tests/CreateListing.cy.tsx
apps/frontend/tests/component_tests/Homepage.cy.tsx

Logout on Mobile
Cursor pointer over `Create Listing` and `Logout` in AccountSidebar.
Closes #282 
Closes #284

Allow logout on mobile and correct cursor pointers

---

.github/workflows/backend.yml
apps/backend/listing/tests/createListing.test.ts
apps/backend/review/package.json
apps/backend/user/package.json

CI testings for backend got disabled. This is bad, lets re-enable it.
Closes #301
Observe CI passing

[CI] Backend tests were disabled

---

apps/backend/lib/package-lock.json
apps/backend/lib/package.json
apps/backend/lib/src/pagination.test.ts
apps/backend/lib/src/pagination.ts

Just the one middleware. All it does is ensure that the `num_items` and `offset` fields are on the req.body so that any endpoints implementing pagination can implement pagination like the following:
```
await db.query("
...
LIMIT $X OFFSET $Y",
[..., req.body.num_items, req.body.offset]);
```
Closes #119 
- [ x ] The code includes tests if relevant
- [ x ] I have *actually* self-reviewed my changes and done QA

Added pagination middleware + improved docker config

---

apps/data/mailserver/Dockerfile
apps/data/mailserver/main.cf
docker-compose.yml

Creates the email server container and base service
Closes #21 

[Datalayer] Create email server

---

apps/algorithm/search/src/routes.py

The authorization header was being parsed, but it wasn't being used 
Closes #332
1. Log into the app as a user other than user 5
2. Search some stuff
3. Check your recommendations to see they've updated

Fix search history updating for all users

---

apps/algorithm/recommend/src/api_models.py
apps/algorithm/recommend/src/recommender.py
apps/algorithm/recommend/src/server.py
apps/algorithm/recommend/src/sql_models.py
apps/algorithm/search/src/routes.py
apps/algorithm/search/src/test_server.py
apps/backend/listing/src/getListingById.ts
apps/backend/listing/src/index.ts
apps/backend/listing/tests/getListingByID.test.ts

Recommender clicks need to be integrated with the backend when GET api/listing/{id} is called. Currently, the recommender clicks functionality only works isolated within the recommender and does not integrate with the rest of the application.
This PR also implements authentication to the getListingById backend feature.
This PR also hopefully fixes the flaky recommender test.
This PR also fixes listingIDs not being string instead of numbers for search/recommendations results. This caused listings not being able to be clicked on properly since the listingID wouldn't get recognized by the front-end.
Closes #325 #310 
Relates #196 
Try clicking on listings and see how your recommendations are affected.

Integrate Recommender Clicks Functionality with Backend (Fixes recommendations not displaying)

---

apps/frontend/tests/component_tests/App.cy.tsx
apps/frontend/tests/component_tests/ViewListing.cy.tsx

Hopefully, this is the last PR for a while fixing the frontend tests... It has been run through CI 3 times without any failures so hopefully I didn't just get lucky.
Closes #336
Run the tests in the CI

Fixing the frontend tests... again

---

apps/backend/listing/Dockerfile
apps/backend/message/Dockerfile
apps/backend/review/Dockerfile
apps/backend/user/Dockerfile

Install the missing lib dependencies in the dockerfile.
Closes #338 

[fix] Install lib dependencies in backend

---

apps/data/datalayer/Cargo.lock
apps/data/datalayer/Cargo.toml
apps/data/datalayer/src/email.rs
apps/data/datalayer/src/main.rs
docker-compose.yml

Sends emails from the datalayer to the email server
Closes #328 
1. `docker compose up --build`
2. `docker exec -it martletplace_datalayer bash`
3. `curl -X POST -H 'Content-Type: application/json' -d '{"to": "test@example.com", "subject": "Test email", "body": "Example"}' http://localhost:8302/api/email`

Add ability to send emails from the datalayer's email api

---

apps/frontend/src/components/searchBar.tsx
apps/frontend/src/pages/ViewListing.tsx

Add back messaging routing

---

apps/data/datalayer/src/email.rs

Email html doesn't render.
Closes #350 
Sign up, look at email

Make emails pretty

---

.github/workflows/e2e.yml
README.md
apps/backend/lib/src/auth.ts
apps/backend/listing/Dockerfile
apps/backend/listing/src/index.ts
apps/backend/message/Dockerfile
apps/backend/message/src/index.ts
apps/backend/review/Dockerfile
apps/backend/review/src/index.ts
apps/backend/user/Dockerfile
apps/backend/user/src/index.ts
apps/data/elasticsearch/Dockerfile

Added healthchecks to all 4 backend services
Closes #343 
`docker ps`

Add health checks to backend services

---

docker-compose.yml

There are simply too many docker networks now and they need to go, sorry!
Closes #358

[DX] Remove docker networks

---

.github/PULL_REQUEST_TEMPLATE.md

Delete the comments
Closes #359

[DX] Remove PR template comments

---

apps/observability/jaeger/Dockerfile
apps/proxy/dynamic_config.yml
docker-compose.yml

Create Jaeger docker container
Closes #126

[O11Y] Setup Jaeger tracing

---

apps/observability/collector/Dockerfile
apps/observability/collector/config.yaml
docker-compose.yml

Create the OTEL collector container and env var
Closes #361

[O11Y] Set up OTEL Collector container

---

apps/backend/lib/package-lock.json
apps/backend/lib/package.json
apps/backend/lib/src/otel.ts
apps/backend/listing/src/index.ts
apps/backend/message/src/index.ts
apps/backend/review/src/index.ts
apps/backend/user/src/index.ts

Added OpenTelemetry to the 4 backend services
Closes #363
Watch the traces/spans flowing in at `localhost:16686` after navigating around the website

[O11Y] Set up basic tracing for Backend services

---

apps/backend/listing/package.json
apps/backend/message/package.json
apps/backend/review/package.json
apps/backend/user/package.json
docker-compose.yml

Add hot reloading support to `lib`
Closes #371

[DX] Add hot reloading for `lib`

---

apps/backend/listing/Dockerfile
apps/backend/message/Dockerfile
apps/backend/review/Dockerfile
apps/backend/user/Dockerfile

Improve the Docker caching scheme for all backend services
Closes #372

[DX] Better Docker caching for `lib`

---

apps/backend/lib/src/otel.ts
apps/observability/collector/config.yaml

Ignore these spans
Closes #375

[O11Y] Ignore irrelevant express middleware spans

---

apps/algorithm/recommend/requirements.txt
apps/algorithm/recommend/src/server.py
apps/algorithm/search/requirements.txt
apps/algorithm/search/src/server.py

Setup basic Python instrumentation
Closes #364
Watch the traces/spans flowing in at http://local.martletplace.ca/admin/tracing after navigating around the website

[O11Y] Basic Python instrumentation

---

apps/algorithm/recommend/requirements.txt
apps/algorithm/recommend/src/db.py
apps/algorithm/recommend/src/server.py
apps/algorithm/search/requirements.txt
apps/algorithm/search/src/database.py
apps/algorithm/search/src/routes.py

Add Database + Elasticsearch client instrumentation
Closes #366
Watch the traces/spans flowing in at http://local.martletplace.ca/admin/tracing after navigating around the website

[O11Y] Advanced Algorithm instrumentation

---

apps/data/datalayer/Cargo.lock
apps/data/datalayer/Cargo.toml
apps/data/datalayer/src/elastic.rs
apps/data/datalayer/src/email.rs
apps/data/datalayer/src/main.rs
docker-compose.yml

Adds a proxy for elasticsearch in the datalayer
Closes #33 
1. `docker compose up --build`
2. log in to datalayer container
3. `curl http://elastic:serxdfcghjfc@localhost:8301/martletplace/_search`

Implement elasticsearch proxy

---

apps/backend/lib/src/otel.ts

Fixes a bug in the JS OTEL, now uses BatchSpanProcessor
Closes #392 
docker compose up

Swap processor to BatchSpanProcessor

---

apps/frontend/src/App.tsx
apps/frontend/src/components/CharityCard.tsx
apps/frontend/src/components/CurrentCharity.tsx
apps/frontend/src/pages/Charities.tsx
apps/frontend/src/styles/pageStyles.tsx
apps/frontend/tests/component_tests/Charities.cy.tsx

implement charities page

---

docker-compose.yml

Stops dragonfly from crashing on beefy computers
Closes #435 
Run on TA's computer

[fix] Limit dragonfly

---

apps/frontend/src/App.tsx
apps/frontend/src/pages/CreateNewPassword.tsx
apps/frontend/src/pages/ForgotPassword.tsx
apps/frontend/src/pages/Login.tsx
apps/frontend/src/types.ts
apps/frontend/tests/component_tests/CreateNewPassword.cy.tsx
apps/frontend/tests/component_tests/ForgotPassword.cy.tsx
apps/frontend/tests/component_tests/Login.cy.tsx

implement forget password UI

---

.github/workflows/loadtest.yml

Loadtest is using an old version of Tokio......yep
Closes #456

[Loadtest] Fix security vulnerability in OpenSSL

---

infra/ecs-services.tf
infra/ecs/ecs-module.tf
infra/ecs/variables.tf
infra/security.tf
infra/variables.tf

[Infra] Route based request splitting

---

apps/algorithm/recommend/src/recommender.py
apps/algorithm/recommend/src/server.py

When a user chooses to stop suggesting a certain item, then the item and similar items are no longer recommended to the same user. 
Closes #46 
Go on the website, find an item, choose "not interested", and see it disappear from the recommendations (along with similar items).

Implement the "Stop suggesting this type of item" functionality

---

apps/frontend/tests/component_tests/CreateCharity.cy.tsx

Attempts to fix the flaky tests
Closes #336 
test

Flaky Tests Again

---

infra/ecr.tf
infra/push-containers.sh

[Infra] Create ECR repository

---

infra/ecs-services.tf
infra/ecs/ecs-module.tf
infra/ecs/variables.tf
infra/security.tf
infra/variables.tf

[Infra] Setup ECS module for env & secrets input

---

apps/backend/user/src/login.ts

Add a flag to skip the MFA steps in dev

---

apps/algorithm/recommend/src/recommender.py

Refactoring the recommender
Closes #475

Refactor recommender

---

apps/backend/listing/Dockerfile
apps/backend/listing/package-lock.json
apps/backend/listing/package.json
apps/backend/message/Dockerfile
apps/backend/message/package-lock.json
apps/backend/message/package.json
apps/backend/review/Dockerfile
apps/backend/review/package-lock.json
apps/backend/review/package.json
apps/backend/user/Dockerfile
apps/backend/user/package-lock.json
apps/backend/user/package.json
docker-compose.yml

[Backend] Production-ize containers

---

apps/frontend/Dockerfile
docker-compose.yml

[Frontend] Create production ready container definition

---

apps/data/database/initdb.sql
apps/data/database/populatedb.sql

Added database tables for organizations and charities, and some sample data. Also added a connecting table `charity_organization` because of their many-to-many relationship. 
Closes #431

Added organizations and charities database tables

---

infra/ecr.tf
infra/ecs-services.tf
infra/push-containers.sh

[Infra] Host Frontend on AWS

---

apps/backend/listing/package.json
apps/backend/message/package.json
apps/backend/review/package.json
apps/backend/user/package.json

[Backend] Minify ESBuild output

---

infra/database.tf
infra/ecs-services.tf
infra/iam.tf
infra/network.tf
infra/opensearch.tf

[Resops] Add opensearch

---

apps/backend/listing/src/index.ts
apps/backend/message/src/index.ts
apps/backend/review/src/index.ts
apps/backend/user/src/index.ts

Lower log levels
Closes #443
Observe terminal when making requests

[Backend] Don't log non-error requests to console

---

docker-compose.yml

[Compose] Add build target

---

apps/algorithm/recommend/Dockerfile
apps/algorithm/recommend/requirements.txt
apps/algorithm/search/Dockerfile
apps/algorithm/search/requirements.txt
apps/backend/listing/Dockerfile
apps/backend/message/Dockerfile
apps/backend/review/Dockerfile
apps/backend/user/Dockerfile

Create productionized containers for Py services
Closes #406

[Algorithm] Add production container defintions

---

apps/data/database/Dockerfile
apps/data/database/initdb.sql
apps/data/database/populatedb.sql
apps/data/database/trainingData.sql
docker-compose.yml
infra/.gitignore
infra/.terraform.lock.hcl
infra/database.tf
infra/db-init.sh

[Infra] Database seeding

---

infra/.terraform.lock.hcl
infra/db-init.sh
infra/ecs-services.tf
infra/jwt.tf

[Infra] Add jwt keys

---

infra/ecr.tf
infra/ecs-services.tf
infra/ecs/ecs-module.tf
infra/ecs/variables.tf
infra/push-containers.sh

[Infra] Link OTEL Collector with TF

---

infra/ecs-services.tf

[Infra] Host Backend services on AWS Cloud

---

apps/algorithm/recommend/Dockerfile
apps/algorithm/recommend/src/config.py
apps/algorithm/recommend/src/recommender.py
docker-compose.yml
infra/ecs-services.tf

[Infra] Host recommender on AWS Cloud

---

apps/backend/lib/src/otel.ts

[backend] Add query statements to spans

---

apps/frontend/src/components/listingCard.tsx
apps/frontend/src/pages/CreateListing.tsx
apps/frontend/src/pages/EditListing.tsx
apps/frontend/src/pages/MyListings.tsx
apps/frontend/src/pages/messages/Messages.tsx
apps/frontend/src/styles/pageStyles.tsx
apps/frontend/tests/component_tests/CreateListing.cy.tsx
apps/frontend/tests/component_tests/EditListing.cy.tsx
apps/frontend/tests/component_tests/Messages.cy.tsx
apps/frontend/tests/component_tests/MyListings.cy.tsx

Fixed the majority of issues that the TA had on the last sprint... I think...
_Also removed validation on load_
_although I have no idea why the TA doesn't think it's responsive_
- Description is required to create a listing
- A non-zero price is required for a listing
- Listing prices get rounded to nearest whole number
----
In another PR, every console.error will either need to be removed or modified to say everything is fine, even if it isn't
Closes #505 
See this issue for the TA's feedback 
Run the application or run npm test

Sprint 2 feedback fixes

---

apps/backend/listing/src/createListing.ts
apps/backend/listing/src/updateListing.ts
apps/data/database/initdb.sql

Last sprint there were a couple issues with creating/editing a listing which can be seen in the following along with the fixes I did.
I made this PR since backend seems quite busy, and hopefully this is an easy/non-contentious fix.
- **Description is required to create a listing**
- Since empty strings are false, change the verification of a request to ensure that description is a string
- **A non-zero price is required for a listing**
- Since 0 is false, changed the verification of a request to ensure a price is not negative
- **Listing prices get rounded to nearest whole number**
- In the database, price was stored as an integer which means that nothing can have a fractional price, fixed by changing int to Decimal(10,2)
Closes #505 
Create and/or edit a listing with the above edge …

Fixed Backend Errors when Creating and Editing Listings 

---

apps/backend/charity/Dockerfile

[Backend] Fix charity dockerfile

---

apps/algorithm/recommend/Dockerfile
apps/algorithm/search/Dockerfile
apps/algorithm/search/requirements.txt
apps/algorithm/search/src/routes.py
apps/algorithm/search/src/test_server.py
docker-compose.yml
infra/ecs-services.tf
infra/ecs/ecs-module.tf
infra/ecs/variables.tf
infra/iam.tf
infra/jwt.tf
infra/opensearch.tf
infra/push-containers.sh
infra/variables.tf

[Infra] Add OpenSearch Misery

---

apps/data/pgsync/Dockerfile
apps/data/pgsync/supervisord.conf
docker-compose.yml

[PGSync] Implement omnibus container with cache

---

apps/frontend/src/components/CharityCard.tsx
apps/frontend/src/components/CurrentCharity.tsx
apps/frontend/src/pages/Charities.tsx
apps/frontend/tests/component_tests/Charities.cy.tsx

fix integration errors for charities page

---

apps/frontend/src/components/searchBar.tsx

Fixed the search history, it wasn't updating right away after making a search
Closes #505

Fixed search history updating

---

apps/data/pgsync/Dockerfile
apps/data/pgsync/supervisord.conf

[PGSync] Fix local development issues

---

infra/ecs/ecs-module.tf
infra/ecs/variables.tf

[Infra] Optional healthchecks (for non HTTP services)

---

infra/ecr.tf
infra/ecs-services.tf
infra/push-containers.sh

[Infra] Host Charity service

---

apps/backend/charity/src/getCurrentCharity.ts
test/load/src/main.rs

[Loadtest] Add Charity endpoints

---

infra/ecs-services.tf
infra/ecs/ecs-module.tf
infra/ecs/variables.tf

[Infra] Configurable scaling parameters

---

apps/observability/collector/config.yaml

[O11y] Replaced #\d with ? in db spans

---

docker-compose.yml
infra/ecr.tf
infra/ecs-services.tf
infra/push-containers.sh
test/load/Cargo.lock
test/load/Cargo.toml
test/load/Dockerfile
test/load/src/main.rs

[Infra] Host goose on AWS

---

apps/frontend/src/App.tsx
apps/frontend/src/pages/Profile.tsx

Fixes a bug with wiping user id when resetting bio
Closes #546 
See issue

Fixed wiping UserID

---

apps/backend/user/src/getUserSearchHistory.ts
apps/frontend/src/components/searchBar.tsx

keep space between search words in ui

---

apps/data/datalayer/Cargo.lock
apps/data/datalayer/Cargo.toml
apps/data/datalayer/src/image.rs
apps/data/datalayer/src/jwt.rs
apps/data/datalayer/src/main.rs
docker-compose.yml

[datalayer] Add image auth

---

apps/backend/message/src/createMessage.ts
apps/backend/message/src/getMessages.ts
apps/backend/message/src/index.ts
apps/backend/message/tests/createMessageTest.test.ts
apps/backend/message/tests/getMessagesTest.test.ts

Minor security improvement: ensures the current user is part of the message thread they're trying to interact with
Closes #429

Check that the user is part of a listing when creating/getting messages

---

apps/backend/charity/src/getCharities.ts
apps/backend/charity/tests/getCharities.test.ts

Charity fund calculation is now correctly done on /charities. Before it just worked properly on /currentCharity
The calculation was taken from /currentCharity where it works properly
Closes #550
- Go to charities page
- Look at the result (it should be a very big number). It used to be 400 which is obviously wrong

Fixed charity fund calculation for /api/charities

---

test/load/local.sh
test/load/src/main.rs

[loadtest] Fix POST listing

---

apps/data/datalayer/Dockerfile

[datalayer] better docker

---

apps/frontend/src/pages/CreateListing.tsx
apps/frontend/src/pages/EditListing.tsx

Fixed form validation in regards to price
Closes #553 
Run the application

Fixed the validation

---

apps/backend/charity/src/getCharities.ts
apps/backend/charity/src/getCurrentCharity.ts
apps/backend/listing/src/createListing.ts
apps/backend/listing/src/updateListing.ts
apps/backend/listing/tests/updateListing.test.ts
apps/data/database/populatedb.sql
apps/frontend/src/components/CharityCard.tsx
apps/frontend/src/components/CurrentCharity.tsx
apps/frontend/src/pages/Charities.tsx

Fixes incorrect query for summing up charity funds, and fixes a typo on the frontend which was not following the API spec (there appeared to be a duplicate return from the getCharities query, listingscount and listingsCount, we only want listingsCount).
Also has a few visual improvements for demo purposes. The full process of creating a listing, marking for charity, and viewing an increased charity funds donated/listing count works on this branch.
Includes fix in fix-listing-endpoints-charities
Closes #566

Demo charity fixes

---

apps/backend/user/src/getUserSearchHistory.ts

[User] Fix search history API

---

apps/backend/listing/src/createListing.ts
apps/backend/listing/src/updateListing.ts
apps/backend/listing/tests/updateListing.test.ts

query was not referencing charity id properly, so fails to updated. Also updated queries accordingly.
Closes #535

fixed bug with listing charity endpoints

---

apps/frontend/src/components/CharityCard.tsx
apps/frontend/src/components/CurrentCharity.tsx

round funds donated

---

apps/backend/user/src/login.ts
apps/backend/user/src/models/user.ts
apps/backend/user/src/patchUser.ts
apps/frontend/src/pages/Profile.tsx
apps/frontend/src/types.ts

Implement ignoreCharityListings functionality

---

apps/algorithm/recommend/readme.md

Update recommender readme.md
